#!/usr/bin/env bash

set -uexo pipefail

dnf -y install \
    @cosmic-desktop \
    --exclude PackageKit \
    --exclude PackageKit-command-not-found

systemctl enable \
    cosmic-greeter-daemon.service \
    cosmic-greeter.service
