ARG from
FROM $from

ARG target_tag

RUN dnf -y install \
    @cosmic-desktop \
    --exclude PackageKit \
    --exclude PackageKit-command-not-found

RUN systemctl enable \
    cosmic-greeter-daemon.service \
    cosmic-greeter.service

# os-release file
RUN sed -i "s/^PRETTY_NAME=.*/PRETTY_NAME=\"Fedora Linux $target_tag (cosmic)\"/" /usr/lib/os-release

# cleanup
RUN dnf clean all && rm -rf /var/log/*

RUN bootc container lint --no-truncate
