ARG from
FROM $from

COPY etc/ /etc/

RUN dnf -y install \
    sway \
    regreet \
    regreet-config-sway \
    waybar \
    brightnessctl \
    flatpak

RUN systemctl enable greetd.service

# os-release file
RUN sed -i "s/^PRETTY_NAME=.*/PRETTY_NAME=\"Fedora Linux $target_tag (sway)\"/" /usr/lib/os-release

# cleanup
RUN dnf clean all && rm -rf /var/log/*

RUN bootc container lint --no-truncate
