ARG from
FROM $from

COPY etc/ /etc/

RUN dnf -y install \
    niri \
    regreet \
    regreet-config-niri \
    waybar \
    brightnessctl \
    flatpak \
    libwayland-server

RUN systemctl enable greetd.service
