ARG from
FROM $from

ARG target_tag

COPY etc/ /etc/

RUN dnf -y install \
    niri \
    regreet \
    regreet-config-niri \
    waybar \
    brightnessctl \
    flatpak \
    libwayland-server

RUN systemctl enable greetd.service

# os-release file
RUN sed -i "s/^PRETTY_NAME=.*/PRETTY_NAME=\"Fedora Linux $target_tag (niri)\"/" /usr/lib/os-release

# cleanup
RUN dnf clean all && rm -rf /var/log/*

RUN bootc container lint --no-truncate
