#!/usr/bin/env bash

set -uexo pipefail

cp -arfT etc /etc

dnf -y install \
    hyprland \
    regreet \
    regreet-config-hyprland \
    waybar \
    brightnessctl \
    flatpak

systemctl enable greetd.service
