ARG from
FROM $from

COPY etc/ /etc/

RUN dnf -y install \
    hyprland \
    regreet \
    regreet-config-hyprland \
    waybar \
    brightnessctl \
    flatpak

RUN systemctl enable greetd.service
