name: containers
on:
  workflow_call:
    inputs:
      fedora_branch:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      fedora_branch:
        type: choice
        description: 'fedora branch'
        required: true
        options:
          - '42'
          - '43'
          - 'rawhide'
        default: '43'
  push:
    paths:
      - 'desktops/**'

run-name: "containers: fedora ${{ inputs.fedora_branch || 43 }} ${{ github.event_name == 'push' && format(' | {0}', github.event.head_commit.message) || '' }}"

jobs:
  desktops:
    runs-on: ubuntu-24.04-arm
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        device: [nothing-spacewar, oneplus-sdm845, xiaomi-nabu, xiaomi-pipa]
        desktop:
          - name: cosmic
            base: "quay.io/fedora-ostree-desktops/cosmic-atomic"
          - name: hyprland
            base: "quay.io/fedora-ostree-desktops/base-atomic"
          - name: niri
            base: "quay.io/fedora-ostree-desktops/base-atomic"
          - name: sway
            base: "quay.io/fedora-ostree-desktops/sway-atomic"
    steps:
      - name: Checkout pocketblue repo
        uses: actions/checkout@v6
        with:
          repository: pocketblue/pocketblue

      - name: Checkout extra repo
        uses: actions/checkout@v6
        with:
          path: extra

      - name: Merge desktops
        run: cp -arT extra/desktops desktops

      - name: Setup just
        uses: extractions/setup-just@v3

      - name: Build
        id: build
        run: |
          just \
            base_atomic=${{ matrix.desktop.base }} \
            branch=${{ inputs.fedora_branch || 43 }} \
            device=${{ matrix.device }} \
            desktop=${{ matrix.desktop.name }} \
            registry=${{ vars.REGISTRY }} \
            rechunk_suffix=-build \
            build

      - name: Rechunk
        id: rechunk
        run: |
          just \
            base_atomic=${{ matrix.desktop.base }} \
            branch=${{ inputs.fedora_branch || 43 }} \
            device=${{ matrix.device }} \
            desktop=${{ matrix.desktop.name }} \
            registry=${{ vars.REGISTRY }} \
            rechunk_suffix=-build \
            rechunk

      - name: Push
        id: push
        uses: pocketblue/actions/container-push@main
        env:
          username: ${{ vars.REGISTRY_USERNAME != '' && vars.REGISTRY_USERNAME || github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN != '' && secrets.REGISTRY_TOKEN || secrets.GITHUB_TOKEN }}
          registry: ${{ vars.REGISTRY }}
          name: ${{ matrix.device }}-${{ matrix.desktop.name }}
          tag: ${{ inputs.fedora_branch || 43 }}
